%%{init: {'theme': 'base'}}%%
graph TD
    subgraph Contains["包含关系 CONTAINS"]
    n0["nanovllm"] -->|contains| n1["config.py"]
    n0["nanovllm"] -->|contains| n2["llm.py"]
    n0["nanovllm"] -->|contains| n3["sampling_params.py"]
    n0["nanovllm"] -->|contains| n4["__init__.py"]
    n0["nanovllm"] -->|contains| n5["layers"]
    n0["nanovllm"] -->|contains| n6["models"]
    n0["nanovllm"] -->|contains| n7["engine"]
    n0["nanovllm"] -->|contains| n8["utils"]
    n9["learn_notes"] -->|contains| n10["block_hash_chain_2026-01-"]
    n9["learn_notes"] -->|contains| n11["nano-vllm_engine_learning"]
    n9["learn_notes"] -->|contains| n12["vllm_scheduler_decode_202"]
    n8["utils"] -->|contains| n13["context.py"]
    n8["utils"] -->|contains| n14["loader.py"]
    n7["engine"] -->|contains| n15["block_manager.py"]
    n7["engine"] -->|contains| n16["llm_engine.py"]
    n7["engine"] -->|contains| n17["model_runner.py"]
    n7["engine"] -->|contains| n18["scheduler.py"]
    n7["engine"] -->|contains| n19["sequence.py"]
    n6["models"] -->|contains| n20["qwen3.py"]
    n5["layers"] -->|contains| n21["activation.py"]
    n5["layers"] -->|contains| n22["attention.py"]
    n5["layers"] -->|contains| n23["embed_head.py"]
    n5["layers"] -->|contains| n24["layernorm.py"]
    n5["layers"] -->|contains| n25["linear.py"]
    n5["layers"] -->|contains| n26["rotary_embedding.py"]
    n5["layers"] -->|contains| n27["sampler.py"]
    end